### PR TITLE
feat:show UI docs in developer portal [devrel-18]

### PR DESCRIPTION
**Pull request by Topener**
This PR adds the UI documentation to the developer portal

- [x] Show UI Components
- [x] Show non-web specific UI docs
- [x] Migrate Storybook Demo's

### CODE REVIEW

**Review by kabaros — COMMENTED** [review]
the code looks good for me - do you know why the netlify preview link is not showing?

**Comment by Topener** [comment]
Netlify link is in the checks section, click the "details" link on the 4th item which is called `netlify/...`

**Comment by kabaros** [comment]
the merging looks good - I have a couple of questions:
1. Will the other parts from the UI docs, like the Principles and Patterns of the design system live here as well?  
2. I think it would be great to think about the information architecture aspect after the merging though. I feel like the Ui Library and design system deserve to be a top-level item, and all the scattered bits and pieces under Tutorial for example, should be grouped together under this one category. This can come later of course, but just want to see what are your thoughts.

**Comment by Topener** [comment]
Great questions! 

UI has it's top-level item under "design" as that term covers it better imho, but URL isn't yet updated so maybe that would need updating too? This is where the principles stuff live

https://deploy-preview-163--dhis2-developer-portal.netlify.app/ui

Only the components right now have moved to the web dev section. Keep in mind the top-level navigation design is in need of redesign itself which is covered here https://dhis2.atlassian.net/browse/DEVREL-34

**Comment by kabaros** [comment]
maybe "Design System" as title, or even "UI & Design System" - and yeah, I would update the URL (unless that has SEO ramifications).

**Review by kabaros — APPROVED** [review]

**Comment by amcgee** [comment]
I agree with @kabaros that we should think a bit more deeply about the information architecture of different types of documentation.  I think we can do that in the near future, though - let's get this merged first.

@Topener the netlify build broke after your last commit, could you take a look at that?

**Comment by amcgee** [comment]
```
frequent broken links are linking to:
- /ui
- /ui/principles/content-communication
```

**Comment by Topener** [comment]
@amcgee Broken links are solved now! Agree on those points as well!

**Review by amcgee — APPROVED** [review]

**Pull request merged**
