### PR TITLE
CHORE: adding newsletter signup form to developer community page

### PR DESCRIPTION
**Pull request by gassims**
I added the Newsletter Signup form to the community page (https://developers.dhis2.org/community). I tested in a local instance and it's working fine. Additionally, the "Technical & Support" was autoselected and added.

The new addition is marked as red:
image

image

@amcgee @Topener please have a look! Thanks!

### CODE REVIEW

**Comment by Topener** [comment]
Hey @gassims, thanks! But it looks like this page isn't visitable from the navigation. Looks like the community section also needs a few more changes to make it up-to-date again. 

But maybe it's better to add a "newsletter" page to the "community" section of the documentation. Could you move it over to it's own file with a short introduction/text?

**Review by gassims — COMMENTED** [review]
@Topener created a new page for the newsletter and a css file for the community-pages. Added the newsletter page to the sidebar. Please have a look! Thanks!

**Review by Topener — CHANGES_REQUESTED** [review]
@gassims I've submitted a formatting commit for the mdx file, and a few tiny styling adjustments. Other than that, looks good to me!

I do think we need a new embed ID though, which can be generated at Make

**Review by gassims — COMMENTED** [review]
Looks good! :) Thanks!

**Comment by gassims** [comment]
> I do think we need a new embed ID though, which can be generated at Make, as the current redirect is not correct

Great, thanks for the clarification! I updated the id on Make and now it redirects to the same page. You are free to make more changes on Make. Thanks! 👍

**Review by Topener — APPROVED** [review]
LGTM!

**Pull request merged**
