### PR TITLE
adding a page to list developer meetup attendees

### PR DESCRIPTION
**Pull request by gassims**
Please have a look at this suggested page. I'm not expecting a commit as much as a discussion or suggestions. I hope you like the idea.

We're pulling the list of Developer Meetup Attendees directly from the CoP using API, see screenshot:
chrome_A1NskdEbaw

### CODE REVIEW

**Comment by KaiVandivier** [comment]
Hey @gassims, thanks for sharing! 😊 Nice additions 🙂

I have a few thoughts I can share:

1. The randomizing algorithm can be improved -- as it is, items tend not to travel _too_ far from their original positions, because only the _comparison_ function is random, not the final position in the list. As a result, people at the end of the list tend not to appear at the top. Here's a simple randomizing algorithm you could use for a more complete "shuffle":
```js
function randomizeOrder(arr) {
    const arrAndRandomIndexes = arr.map((e) => ({ e, i: Math.random() }))
    arrAndRandomIndexes.sort((a, b) => a.i - b.i)
    return arrAndRandomIndexes.map(({ e }) => e)
}
```

2. In my opinion, I think the list of badge-holders should be _even more_ dense to make the page even smaller 🙂 maybe the space between users can be smaller

3. I noticed that the spacing of the items can change on hover, which can make the items jitter around a bit (see video) -- you might try using the `outline` property instead of `border` on hover, which I believe doesn't affect the layout space 🙂

https://github.com/dhis2/developer-portal/assets/49666798/fa6f0de5-50f1-48b6-9d53-9479b79c29e5

Thanks for sharing! I like the styles on the user badges 🙂

**Comment by Topener** [comment]
Awesome feature @gassims, thanks for putting this together 

Great feedback @KaiVandivier, the "jumping around" caught my attention too. 

There's both a margin and a padding on the layout, and both are quite big, removing one of them or making both about half would fix a big problem.

Screenshot 2023-06-02 at 16 23 57

I also recommend moving the CSS from in-line to a module.css file, making the code much cleaner.

**Comment by gassims** [comment]
Aye, aye! 😁 I'm grateful for your direction @KaiVandivier and @Topener! I have made the changes and I hope it's better now.

I learned something new about outline vs border which is going to be so helpful in the long run. Also, for the margins, Infima's classes were already adding margins and padding so when I added more it was too much so I kept it to the minimum; additionally, I had flex justify-content to space-between which apparently doubled the spacing so I changed to center instead (with margin: 0.5vw I think it's minimum).

Also, the randomFunction is really helpful, thanks for the suggestion Kai! (:

The inline styling has been moved to badges.css (should've done that from the start 😅) Thanks Rene!


If it looks like there can be more changes, please let me know! Thanks! 👍


P.S.
I was busy with the annual conference so sorry for my delayed response.

**Review by Topener — CHANGES_REQUESTED** [review]
That is a BIG improvement ! Like it a lot. 

I think the only change I still see that would improve the page is to add a little more spacing around this block, and a little spacing below the badge icon itself.

Screenshot 2023-06-19 at 09 55 25

**Review by KaiVandivier — APPROVED** [review]
Nice @gassims, I think this looks good 🙂 my last suggestion is that the `BadgeList.js` file looks like it needs some formatting 🙂

**Comment by gassims** [comment]
> That is a BIG improvement ! Like it a lot.

Thanks! I increased the spacing between the elements in the badge info section and gave the badge a bigger size.



> Nice @gassims, I think this looks good 🙂 my last suggestion is that the `BadgeList.js` file looks like it needs some formatting

Thanks! :) I edited some lines and used VS Code to give it a better formating (Ctrl+k + F)

**Review by Topener — APPROVED** [review]
Changes look good to me, awesome!

**Pull request merged**
