### PR TITLE
docs: add data-query-playground guide

### PR DESCRIPTION
**Pull request by deboragaleano**
This PR adds the guide: "How to use the Data Query Playground"

### CODE REVIEW

**Review by Mohammer5 — COMMENTED** [review]
Undocumented feature: Queries/Mutations can be executed by hitting Ctrl+Enter
That way you don't have to use the mouse when both hands are on the keyboard

**Comment by deboragaleano** [comment]
> Undocumented feature: Queries/Mutations can be executed by hitting Ctrl+Enter
> That way you don't have to use the mouse when both hands are on the keyboard

Thank you so much @Mohammer5 for the suggestion! It's great to know this actually 💯 
I added the following, what do you think?

**Tip:** 
Useful keyboard shortcut: You can also execute **`Query`** and **`Mutation`** without a mouse by pressing **`Ctrl+Enter`** ⚡️

**Comment by Mohammer5** [comment]
:+1: nice

**Review by amcgee — APPROVED** [review]
LGTM 👍

**Pull request merged**
