### PR TITLE
docs: update Docker Compose example and wording

### PR DESCRIPTION
**Pull request by radnov**
Update the Docker Compose example with the correct DB dump variable ([`DHIS2_DB_DUMP_URL`](https://github.com/dhis2/dhis2-core/blob/master/docker-compose.yml#L50)) and remove the suggestion to only download the docker-compose file, as it doesn't really work.

### CODE REVIEW

**Review by teleivo — APPROVED** [review]
I think it would also be ok to simply link to the core repo l. This way the instructions will always be up to date 🙂

**Comment by radnov** [comment]
> I think it would also be ok to simply link to the core repo l. This way the instructions will always be up to date 🙂
@teleivo I'm torn because I like having the quick example in there, but it's indeed bound to drift from the instructions in the `dhis2/dhis2-core`. 🤔

**Comment by Topener** [comment]
I think linking the repository can be a good thing. Do we also want to prioritize docker compose above the `D2 cluster CLI`? Might be better to reverse the order there, and link the repository in a reference section maybe?

**Comment by radnov** [comment]
> I think linking the repository can be a good thing. Do we also want to prioritize docker compose above the `D2 cluster CLI`? Might be better to reverse the order there, and link the repository in a reference section maybe?

@Topener 

The dhis2-core repo readme is [already linked](https://github.com/dhis2/developer-portal/blob/a7327f68fcf34f00dc189e7ba128ccc20cd844d7/docs/tutorials/dhis2-docker.md#run-dhis2-in-docker-with-docker-compose) in the Docker Compose section, but the question is whether we should remove the `docker compose` command example from there and just leave the link?

The order is a bit on the preference side I suppose. To me using `docker compose` is preferable and simpler (if you know about Docker already) and I would assume that's the case for most "developers". I'm fine with reversing the order, though.

I'm not completely sure what you mean by "_link the repository in a reference section maybe_", though. 🤔

**Comment by radnov** [comment]
@Topener @teleivo I removed the examples for both Compose and `d2 cluster` and swaped their places.

**Review by Topener — COMMENTED** [review]
I think, overall, this is a good change, and I approve.

But I'm conflicted about removing the examples. While the links do indeed provide the answers, and most likely the up-to-date ones at that, but having the users read multiple pages on multiple sites makes things confusing and harder to on-board.

I think it would be better to keep the examples, but add a small note (https://docusaurus.io/docs/markdown-features/admonitions) they can find more information at those places. 

I think the argument "it might get out of date" is more an incentive to make sure it doesn't, than to just remove it. Onboarding and reading docs should be easy :) 

Let me know your thoughts

**Comment by radnov** [comment]
@Topener I agree that we should make it easier for the user and just keep the examples updated. 👍 

I brought back the examples and added Docasaurus notes with links to the main sources for both sections.

**Review by Topener — APPROVED** [review]
LGTM!

**Pull request merged**
